export const actionTypes = {
    SET_PRODUCTS: 'SET_PRODUCTS',
    SELECTED_PRODUCT: 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
    ADD_TO_CART: 'ADD_TO_CART',
    ADJUST_ITEM_QTY: 'ADJUST_ITEM_QTY',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    LOAD_CURRENT_ITEM: 'LOAD_CURRENT_ITEM',
    SET_CART_PRODUCTS: 'SET_CART_PRODUCTS',
}